### ISSUE TITLE
Issue with HTTP Header Name regex

### ISSUE THREAD

**Issue by LordMike** [samsalisbury/Sublime-HTTP#1]
Original: https://github.com/github/markup/issues/1229

I've found an issue in HTTP headers, where numbers are not interpreted correctly.

I think the issue is [here](https://github.com/samsalisbury/Sublime-HTTP/blob/0099998617eb784fa27d8a47e289058d9a6307ab/httpspec.YAML-tmLanguage#L32). From the RFC2616, we can see that a header is defined a `token: <some field>`, and `token` is defined as `1*<any CHAR except CTLs or separators>`.

As I understand it, the regex should then be something like `^([^\(\)\<\>@,;:\\\"\{\} \t\0x00-\0x1F\0x7F]+\:)\s(.*)$`

This matches all characters except the CTL's and Seperators defined:
* Seperators: `(`, `)`, `<`, `>`, `@`, `,`, `;`, `:`, `\` `"`, `/`, `[`, `]`, `?`, `=`, `{`, `}`, ` `, `\t`
* CTL's: `\0x00-\0x1F`, `\0x7F` (any US-ASCII control character (octets 0 - 31) and DEL (127))

Links
* https://tools.ietf.org/html/rfc2616.html#section-4.2 <-- On headers
* https://tools.ietf.org/html/rfc2616.html#section-2.2 <-- On Tokens

And should the Colon be part of the headername?

**Comment by samsalisbury** [comment]
Hi @LordMike I just saw this, I can see the issue over in 
https://github.com/github/markup/issues/1229 are you able to send a PR to fix this? I have a lot on my plate atm so might take a while to get to it otherwise.
