### ISSUE TITLE
GitRepo moved and Package manager cannot find the package

### ISSUE THREAD

**Issue by crisp2u** [samsalisbury/Sublime-HTTP#2]
Sublime Package manager cannot find the package probably because the github repo move. What need to be done to update the github repo in Sublime Package manager ? 

Thanks

**Comment by samsalisbury** [comment]
Hi @crisp2u just got to this under a deluge of notifications, did you find an answer? I stopped using sublime a long time ago, so I'm pretty far away from the ecosystem now I'm afraid, but if you find the reference in the package manager do let me know so we can get it resolved & close this. Thanks.

**Comment by crisp2u** [comment]
No worries, I manually installed the package. The package is [here](https://packagecontrol.io/packages/HTTP%20Spec%20Syntax) but I assume there is some account on the package control site. If you want you can give me access and I'll have a look

**Comment by samsalisbury** [comment]
OK, I found the relevant repo and submitted a PR, thanks for raising this, I'll close it now. See https://github.com/wbond/package_control_channel/pull/7585
